AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/dummy/**/*'
    - '**/*_spec.rb'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'

Metrics/AbcSize:
  Max: 26

Metrics/BlockNesting:
  Max: 3

Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  CountComments: false
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 45

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 7

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Alias:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/BracesAroundHashParameters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false
