language: ruby
dist: precise
sudo: false
rvm:
  - 2.3.1
  - 2.3.4
  - 2.4.1
  - ruby-head
allow_failures:
  - rvm: ruby-head
branches:
  only:
    - master
script:
  - bundle exec rspec spec/
bundler_args: --without production --jobs=3 --retry=3 --path=../vendor/bundle
cache: bundler
