
language: ruby
dist: precise
sudo: false
addons:
apt:
  packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
rvm:
  - 2.3.1
  - 2.3.4
  - 2.4.1
  - ruby-head
allow_failures:
  - rvm: ruby-head
services:
  - mysql
branches:
  only:
    - master
before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bobot_test;'
  - cp spec/travis/database.travis.mysql.yml spec/dummy/config/database.yml
script:
  - bundle exec rubocop
  - bundle exec rspec spec/
bundler_args: --without production --jobs=3 --retry=3 --path=../vendor/bundle
cache: bundler
