default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: bobot_development

test:
  <<: *default
  database: bobot_test

production:
  <<: *default
  database: bobot_production
